language: node_js

node_js: "10"

cache: npm

env:
    - MONGO_USER_ID=$MONGO_USER_ID MONGO_USER_KEY=$MONGO_USER_KEY
    
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_KEY
  region: us-east-2
  app: Space Dashboard
  env: master-spacedashboard
  bucket_name: elasticbeanstalk-us-east-2-583257580903
  bucket_path: Code
