version: 2

# List of jobs
jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:10.15.0
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: npm install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            # run tests!
            - run: npm test

    # The deploy job
    deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:10.15.0
        steps:
            echo "Deploying..."
            # Steps to be added

workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - build
            - deploy
